const blankLine = '  |   |  ';
console.log('This is what an empty board look like:');
console.log(blankLine);
console.log(blankLine);
console.log(blankLine);
const guessLine ='1 |   |  ';
console.log('This is what a board with a guess and a bomb would look like:');
const bombLine = '  | B |  ';
console.log(guessLine);
console.log(bombLine);
console.log(blankLine);
